# Generated by Django 5.0.7 on 2024-08-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_aappgarticlespost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aappgarticlespost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
