# Generated by Django 5.0.7 on 2024-09-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_alter_aappgarticlespost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aappgcustomuser',
            name='city',
            field=models.CharField(default='Lelouma', max_length=255),
        ),
    ]
