# Generated by Django 5.0.7 on 2024-09-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_aappgcustomuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='aappgcustomuser',
            name='telephone',
            field=models.CharField(blank=True, default='224 666 66 66', max_length=255),
        ),
    ]
