# Generated by Django 5.0.7 on 2024-09-22 21:28

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0007_aappgcustomuser_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='aappgcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 21, 28, 43, 893290, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='aappgcustomuser',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='aappgcustomuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
