# Generated by Django 5.0.7 on 2024-09-23 15:19

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0008_aappgcustomuser_email_verification_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aappgcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 15, 19, 7, 342627, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='aappgcustomuser',
            name='email_verification_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
