# Generated by Django 5.0.7 on 2024-09-23 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0010_alter_aappgcustomuser_email_verification_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aappgcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 15, 42, 47, 386663, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='aappgcustomuser',
            name='email_verification_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
