# Generated by Django 5.0.7 on 2024-09-29 21:03

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0014_aappgarticlespost_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aappgcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 9, 30, 21, 3, 38, 82939, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.CreateModel(
            name='AappgCommunique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
